---
name: Lint Code Base

on: [push, pull_request]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: super-linter/super-linter/slim@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANSIBLE_DIRECRTORY: "."
          ANSIBLE_CONFIG_FILE: ".ansible-lint"
          YAML_CONFIG_FILE: ".yaml-lint"
          BASH_SEVERITY: "error"
          GITHUB_ACTIONS_COMMAND_ARGS: "-shellcheck="
          VALIDATE_BASH": false
